name: Detect flutter version
description: Detect flutter version

outputs:
  version:
    description: flutter_version
    value: ${{ steps.detect-flutter-version.outputs.version }}

runs:
  using: composite
  steps:
    - name: Detect flutter version
      id: detect-flutter-version
      shell: bash
      run: |
        DETECT_VERSION=$(jq -r '.flutter' ./.fvmrc)
        echo Detect version: ${DETECT_VERSION}
        if [ "${DETECT_VERSION}" != "null" ]; then
          echo version=${DETECT_VERSION} >> $GITHUB_OUTPUT
        else
          echo "Can't detect flutter version."
          exit 1
        fi
