name: Pull Request Check

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Generate GitHub App token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.CREATE_APP_TOKEN_APP_ID }}
          private-key: ${{ secrets.CREATE_APP_TOKEN_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ steps.generate_token.outputs.token }}

      - name: Detect flutter version
        id: flutter-version
        uses: ./.github/actions/detect-flutter-version

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.flutter-version.outputs.version }}
          cache: true

      - name: Flutter version
        run: flutter --version

      - name: Install dependencies
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: flutter pub get

      - name: Linter
        run: flutter analyze

      - name: Test
        run: flutter test
